#!/usr/bin/env ruby
#
# Ruby equivalent of:
#
#  https://github.com/rdio/rdio-python/blob/master/rdio-call
#

begin
  require 'lib/rdio'
rescue
  require 'rubygems'
  require 'rdio'
end

exit Rdio::Call.new.main ARGV
